---
title: '1'
output: pdf_document
date: "2023-07-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(NMF)
test <- nmf(g1$Original[[1]], rank = 2, method = "brunet")

```

```{r}

```


```{r}
jaccard_bicluster <- function(row_c, col_c, true_r, true_c) {
  # Jaccard
  original_mat <- true_r %*% t(true_c)
  predict_mat <- row_c %*% t(col_c)
  overall <- original_mat + predict_mat
  intersect <- sum(overall == 2)
  union <- sum(overall != 0)
  jaccard <- intersect/union
  
  # F1_score
  diff <- original_mat - predict_mat
  TP <- intersect
  FP <- sum(diff == -1)
  FN <- sum(diff == 1)
  f1_score <- TP/(TP + 0.5*(FP + FN))
  
  return(list("Jaccard" = jaccard, "F_Score" = f1_score))
}

```

```{r}
jaccard_bicluster <- function(row_c, col_c, true_r, true_c) {
  m <- sum(colSums(row_c) != 0) #no of clusters detected
  n <- sum(colSums(true_r) != 0) #no of true clusters
  # if no biclusters detected but some are present
  # return 0
  # if no biclusters present but some are detected - score of 0
  if ((m == 0 && n != 0) || (n == 0 && m != 0)) {
    if (stability) {
      return(0)
    }else{
      return(list("rev" = rep(0, 2), "rel" = rep(0, 2), "f_score" = rep(0, 2)))
    }
  }
  # if no biclusters present and none detected - score of 1
  if (m == 0 && n == 0) {
    if (stability) {
      return(1)
    }else{
      return(list("rev" = rep(1, 2), "rel" = rep(1, 2), "f_score" = rep(1, 2)))
    }
  }
  # Jaccard
  original_mat <- true_r %*% t(true_c)
  predict_mat <- row_c %*% t(col_c)
  overall <- original_mat + predict_mat
  intersect <- sum(overall == 2)
  union <- sum(overall != 0)
  jaccard <- intersect/union
  
  # F1_score
  diff <- original_mat - predict_mat
  TP <- intersect
  FP <- sum(diff == -1)
  FN <- sum(diff == 1)
  f1_score <- TP/(TP + 0.5*(FP + FN))
  
  return(list("Jaccard" = jaccard, "F_Score" = f1_score))
}



```

```{r}
jaccard_bicluster(z1$row_clusters[[1]], z1$col_clusters[[1]], cbind(c(rep(1, 50), rep(0, 50), rep(0, 50)), c(rep(0, 50), rep(1, 50), rep(0, 50)), c(rep(0, 50), rep(0, 50), rep(1, 50))), z1$col_clusters[[1]])

```

```{r}
image((z1_shuffle$row_clusters[[1]] %*% t(z1_shuffle$col_clusters[[1]]))[, order(g1$Indices[[2]])][order(g1$Indices[[1]]), ])

image(z1$row_clusters[[1]] %*% t(z1$col_clusters[[1]]))

jaccard_bicluster(z1$row_clusters, z1$col_clusters, )

```

```{r}
show_image_each_view <- function(generate_blocks, restMultiNMTF, restMultiNMTF_shuff, n_view) {
  # generate_blocks refer to the function to generate data
  # restMultiNMTF: result from the function restMultiNMTF_run
  # n_view: the view which would like to be shown
  
  # Original Data
  X_ori <- generate_blocks$Original[[n_view]]
  X_calculated <- restMultiNMTF$Foutput[[n_view]] %*% restMultiNMTF$Soutput[[n_view]] %*% t(restMultiNMTF$Goutput[[n_view]])
  
  Bicluster_ori <- generate_blocks$row_c[[n_view]] %*% t(generate_blocks$col_c[[n_view]])
  Bicluster_calculated <- restMultiNMTF$row_clusters[[n_view]] %*% t(restMultiNMTF$col_clusters[[n_view]])
  
  # Shuffled Data
  X_ori_shuff <- generate_blocks$Shuffled[[n_view]]
  X_calculated_shuff <- restMultiNMTF_shuff$Foutput[[n_view]] %*% restMultiNMTF_shuff$Soutput[[n_view]] %*% t(restMultiNMTF_shuff$Goutput[[n_view]])
  
  Bicluster_calculated_shuff <- restMultiNMTF_shuff$row_clusters[[n_view]] %*% t(restMultiNMTF_shuff$col_clusters[[n_view]])
  
  Bicluster_recover <- Bicluster_calculated_shuff[, order(generate_blocks$Indices[[2*n_view]])][order(generate_blocks$Indices[[2*n_view-1]]), ]
  
  Bicluster_recover_manual <- recover_matrix(Bicluster_calculated_shuff)
  
  # Plot images
  image(X_ori)
  title(main = "Original X")
  image(X_calculated)
  title(main = "Calculated X")
  image(Bicluster_ori)
  title(main = "Bicluster")
  image(Bicluster_calculated)
  title(main = "Calculated Bicluster")
  
  image(X_ori_shuff)
  title(main = "Shuffled X")
  image(X_calculated_shuff)
  title(main = "Calculated Shuffled X")
  image(Bicluster_calculated_shuff)
  title(main = "Calculated Shuffled Bicluster")
  image(Bicluster_recover)
  title(main = "Recovered Bicluster")
  image(Bicluster_recover_manual)
  title(main = "Recovered Bicluster Black Box")
  
  return(list("Original" = jaccard_results(row_c=restMultiNMTF$row_clusters[[n_view]], col_c=restMultiNMTF$col_clusters[[n_view]], generate_blocks$row_c[[n_view]], generate_blocks$col_c[[n_view]])))
}

```

```{r}
show_image_each_view(g4, z4_ori_fun, z4_ori_fun_shuffle, 1)

```

```{r}
# All z1 are generated by the original restMultiNMTF_run() function, with KK/LL = c(3, 3, 3)
# X = g1$Original/$Shuffled
# z_test are using the modified one
# z2 and z3 are also using the modified one
# z2 are overlap, z3 are overlap and not fullrank
# z3_O is using the original functions to compare z3_large_sparsity

```

```{r}
show_image_each_view(g4, z4_modified, z4_modified_shuffle, 1)

```

```{r}
show_image_each_view(g6, z6, z6_shuffle, 1)

```

```{r}
recover_matrix <- function(matrix) {
  mat <- matrix
  list_r <- c(1:nrow(matrix))
  list_c <- c(1:ncol(matrix))
  order <- NULL
  i = 1
  while (length(list_r) != 0) {
    row <- mat[i, ]
    
    filter <- c(which(row_distances < 10))
    order <- c(order, filter)
    list_r <- list_r[-filter]
    mat <- mat[-filter, ]
    i <- list_r[1]
  }
  matrix <- matrix[order, ]
  return(matrix)
}


```

```{r}
recover_matrix <- function(matrix) {
  list_r <- c(1:nrow(matrix))
  list_c <- c(1:ncol(matrix))
  dist_matrix_r <- as.matrix(dist(matrix, diag = TRUE, upper = TRUE))
  dist_matrix_c <- as.matrix(dist(t(matrix), diag = TRUE, upper = TRUE))
  tracking_order_r <- NULL
  tracking_order_c <- NULL
  i = 1
  
  while (length(list_c) != 0) {
    filter <- c(which(dist_matrix_c[, i] < 5))
    filter <- filter[!(filter %in% tracking_order_c)]
    tracking_order_c <- c(tracking_order_c, filter)
    list_c <- list_c[!(list_c %in% filter)]
    i <- list_c[1]
  }
  while (length(list_r) != 0) {
    filter <- c(which(dist_matrix_r[i, ] < 5))
    filter <- filter[!(filter %in% tracking_order_r)]
    tracking_order_r <- c(tracking_order_r, filter)
    list_r <- list_r[!(list_r %in% filter)]
    i <- list_r[1]
  }
  
  matrix <- matrix[tracking_order_r, ][, tracking_order_c]
  return(matrix)
}


```


```{r}
show_image_each_view(g3, z3_test_n_cluster, z3_test_n_cluster_shuffle, 1)

```

```{r}
jaccard_results <- function(row_c, col_c, true_r, true_c, stability = FALSE){
  m <- sum(colSums(row_c) != 0) #no of clusters detected
  n <- sum(colSums(true_r) != 0) #no of true clusters
  # if no biclusters detected but some are present
  # return 0
  # if no biclusters present but some are detected - score of 0
  if ((m == 0 && n != 0) || (n == 0 && m != 0)) {
    if (stability) {
      return(0)
    }else{
      return(list("rev" = rep(0, 2), "rel" = rep(0, 2), "f_score" = rep(0, 2)))
    }
  }
  # if no biclusters present and none detected - score of 1
  if (m == 0 && n == 0) {
    if (stability) {
      return(1)
    }else{
      return(list("rev" = rep(1, 2), "rel" = rep(1, 2), "f_score" = rep(1, 2)))
    }
  }
  samps <- 1:nrow(row_c)
  feats <- 1:nrow(col_c)
  c_list <- NULL
  #initialise storage of jaccard index between pairs
  jac_mat <- matrix(0, nrow = m, ncol = n)
  for (i in 1:m){
    r_i <- samps[row_c[, i] == 1]
    c_i <- feats[col_c[, i] == 1]
    m_i <- cart_prod(r_i, c_i)
    c_list <- c(c_list, m_i)
    for (j in 1:n){
        tr_i <- samps[true_r[, j] == 1]
        tc_i <- feats[true_c[, j] == 1]
        m_j <- cart_prod(tr_i, tc_i)
        jac_mat[i, j] <- jaccard(m_i, m_j)
    }
  }
  if (length(c_list[duplicated(c_list)]) != 0) {
    jac_mat <- jac_mat[!duplicated(c_list), ]
  }
  
  if (stability) {
    return(apply(jac_mat, 2, max))
  }
  rel <- mean(apply(jac_mat, 1, max))
  rev <- mean(apply(jac_mat, 2, max))
  f <- 2 * rel * rev / (rel + rev)
  return(list("rev" = rep(rev, 2), "rel" = rep(rel, 2), "f_score" = rep(f, 2)))
}


```
